services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\MenuBundle\Asset\EncoreExtension:
    autoconfigure: true

  HeimrichHannot\MenuBundle\EventListener\Contao\LoadDataContainerListener: ~
